// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const insertFeed = `-- name: InsertFeed :one
 INSERT INTO feeds (
	url, 
	title, 
	css_sel_container,
	css_sel_start,
	css_sel_stop,
	html_extraction_strategy,
	last_fetched,
	folder_name
) VALUES (
	?, 
	?, 
	?, 
	?, 
	?, 
	?, 
	CURRENT_TIMESTAMP,
	?
) RETURNING id, url, title, folder_name, last_fetched, css_sel_container, css_sel_start, css_sel_stop, html_extraction_strategy
`

type InsertFeedParams struct {
	Url                    string
	Title                  string
	CssSelContainer        string
	CssSelStart            string
	CssSelStop             string
	HtmlExtractionStrategy string
	FolderName             string
}

func (q *Queries) InsertFeed(ctx context.Context, arg InsertFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, insertFeed,
		arg.Url,
		arg.Title,
		arg.CssSelContainer,
		arg.CssSelStart,
		arg.CssSelStop,
		arg.HtmlExtractionStrategy,
		arg.FolderName,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.FolderName,
		&i.LastFetched,
		&i.CssSelContainer,
		&i.CssSelStart,
		&i.CssSelStop,
		&i.HtmlExtractionStrategy,
	)
	return i, err
}

const insertOrIgnoreArticle = `-- name: InsertOrIgnoreArticle :exec
INSERT OR IGNORE INTO articles (
	feed_id, 
	title, 
	link, 
	published, 
	date_found,
	summary,
	scraped_html,
	formatted_html
) VALUES (
	 ?, 
	 ?, 
	 ?, 
	 ?,
	 ?, 
	 ?, 
	 ?, 
	 ? 
 )
`

type InsertOrIgnoreArticleParams struct {
	FeedID        int64
	Title         string
	Link          string
	Published     *time.Time
	DateFound     *time.Time
	Summary       string
	ScrapedHtml   string
	FormattedHtml string
}

func (q *Queries) InsertOrIgnoreArticle(ctx context.Context, arg InsertOrIgnoreArticleParams) error {
	_, err := q.db.ExecContext(ctx, insertOrIgnoreArticle,
		arg.FeedID,
		arg.Title,
		arg.Link,
		arg.Published,
		arg.DateFound,
		arg.Summary,
		arg.ScrapedHtml,
		arg.FormattedHtml,
	)
	return err
}

const insertScraperRan = `-- name: InsertScraperRan :one
INSERT INTO log (
	articles_created, 
	run_type,
	time_ran
) VALUES (
	?,
	?, 
	CURRENT_TIMESTAMP
) RETURNING id, time_ran, run_type, articles_created
`

type InsertScraperRanParams struct {
	ArticlesCreated int64
	RunType         string
}

func (q *Queries) InsertScraperRan(ctx context.Context, arg InsertScraperRanParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, insertScraperRan, arg.ArticlesCreated, arg.RunType)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.TimeRan,
		&i.RunType,
		&i.ArticlesCreated,
	)
	return i, err
}

const selectAllFeeds = `-- name: SelectAllFeeds :many
SELECT id, url, title, folder_name, last_fetched, css_sel_container, css_sel_start, css_sel_stop, html_extraction_strategy from feeds
`

func (q *Queries) SelectAllFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, selectAllFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.FolderName,
			&i.LastFetched,
			&i.CssSelContainer,
			&i.CssSelStart,
			&i.CssSelStop,
			&i.HtmlExtractionStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectArticleByFeedIDAndLink = `-- name: SelectArticleByFeedIDAndLink :one
SELECT id, feed_id, title, link, published, date_found, scraped_html, markdown, formatted_html, summary, read, starred FROM articles WHERE feed_id = ? AND link = ?
`

type SelectArticleByFeedIDAndLinkParams struct {
	FeedID int64
	Link   string
}

func (q *Queries) SelectArticleByFeedIDAndLink(ctx context.Context, arg SelectArticleByFeedIDAndLinkParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, selectArticleByFeedIDAndLink, arg.FeedID, arg.Link)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Link,
		&i.Published,
		&i.DateFound,
		&i.ScrapedHtml,
		&i.Markdown,
		&i.FormattedHtml,
		&i.Summary,
		&i.Read,
		&i.Starred,
	)
	return i, err
}

const selectArticleByID = `-- name: SelectArticleByID :one
SELECT id, feed_id, title, link, published, date_found, scraped_html, markdown, formatted_html, summary, read, starred FROM articles WHERE id = ?
`

func (q *Queries) SelectArticleByID(ctx context.Context, id int64) (Article, error) {
	row := q.db.QueryRowContext(ctx, selectArticleByID, id)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Link,
		&i.Published,
		&i.DateFound,
		&i.ScrapedHtml,
		&i.Markdown,
		&i.FormattedHtml,
		&i.Summary,
		&i.Read,
		&i.Starred,
	)
	return i, err
}

const selectArticleCountByFeedID = `-- name: SelectArticleCountByFeedID :one
SELECT COUNT(*) FROM articles WHERE feed_id = ?
`

func (q *Queries) SelectArticleCountByFeedID(ctx context.Context, feedID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, selectArticleCountByFeedID, feedID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const selectArticlesByFeedIDWithLimit = `-- name: SelectArticlesByFeedIDWithLimit :many
SELECT
   a.id as article_id,
	a.link as article_link,
	a.title as article_title,
	a.starred as article_stars,
	a.published as article_published,
	a.read as article_read,
	a.feed_id as article_feed_id,
    f.title as feed_title
FROM articles a
    INNER JOIN feeds f ON f.id = a.feed_id
WHERE a.feed_id  = ?
ORDER BY published DESC
LIMIT ? OFFSET ?
`

type SelectArticlesByFeedIDWithLimitParams struct {
	FeedID int64
	Limit  int64
	Offset int64
}

type SelectArticlesByFeedIDWithLimitRow struct {
	ArticleID        int64
	ArticleLink      string
	ArticleTitle     string
	ArticleStars     int64
	ArticlePublished *time.Time
	ArticleRead      int64
	ArticleFeedID    int64
	FeedTitle        string
}

func (q *Queries) SelectArticlesByFeedIDWithLimit(ctx context.Context, arg SelectArticlesByFeedIDWithLimitParams) ([]SelectArticlesByFeedIDWithLimitRow, error) {
	rows, err := q.db.QueryContext(ctx, selectArticlesByFeedIDWithLimit, arg.FeedID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectArticlesByFeedIDWithLimitRow
	for rows.Next() {
		var i SelectArticlesByFeedIDWithLimitRow
		if err := rows.Scan(
			&i.ArticleID,
			&i.ArticleLink,
			&i.ArticleTitle,
			&i.ArticleStars,
			&i.ArticlePublished,
			&i.ArticleRead,
			&i.ArticleFeedID,
			&i.FeedTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectArticlesWithFeedName = `-- name: SelectArticlesWithFeedName :many
SELECT a.id, a.feed_id, a.title, a.link, a.published, a.date_found, a.scraped_html, a.markdown, a.formatted_html, a.summary, a.read, a.starred, f.title AS feed_title FROM articles a INNER JOIN feeds f ON f.id = a.feed_id
`

type SelectArticlesWithFeedNameRow struct {
	ID            int64
	FeedID        int64
	Title         string
	Link          string
	Published     *time.Time
	DateFound     *time.Time
	ScrapedHtml   string
	Markdown      string
	FormattedHtml string
	Summary       string
	Read          int64
	Starred       int64
	FeedTitle     string
}

func (q *Queries) SelectArticlesWithFeedName(ctx context.Context) ([]SelectArticlesWithFeedNameRow, error) {
	rows, err := q.db.QueryContext(ctx, selectArticlesWithFeedName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectArticlesWithFeedNameRow
	for rows.Next() {
		var i SelectArticlesWithFeedNameRow
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.Title,
			&i.Link,
			&i.Published,
			&i.DateFound,
			&i.ScrapedHtml,
			&i.Markdown,
			&i.FormattedHtml,
			&i.Summary,
			&i.Read,
			&i.Starred,
			&i.FeedTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectFeedByID = `-- name: SelectFeedByID :one
SELECT id, url, title, folder_name, last_fetched, css_sel_container, css_sel_start, css_sel_stop, html_extraction_strategy FROM feeds where id = ?
`

func (q *Queries) SelectFeedByID(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRowContext(ctx, selectFeedByID, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.FolderName,
		&i.LastFetched,
		&i.CssSelContainer,
		&i.CssSelStart,
		&i.CssSelStop,
		&i.HtmlExtractionStrategy,
	)
	return i, err
}

const updateArticleByID = `-- name: UpdateArticleByID :one
UPDATE articles SET markdown = ? WHERE id = ? RETURNING id, feed_id, title, link, published, date_found, scraped_html, markdown, formatted_html, summary, read, starred
`

type UpdateArticleByIDParams struct {
	Markdown string
	ID       int64
}

func (q *Queries) UpdateArticleByID(ctx context.Context, arg UpdateArticleByIDParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, updateArticleByID, arg.Markdown, arg.ID)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Link,
		&i.Published,
		&i.DateFound,
		&i.ScrapedHtml,
		&i.Markdown,
		&i.FormattedHtml,
		&i.Summary,
		&i.Read,
		&i.Starred,
	)
	return i, err
}

const updateArticleSetStarredValue = `-- name: UpdateArticleSetStarredValue :one
UPDATE articles SET starred = ? WHERE id = ? RETURNING id, feed_id, title, link, published, date_found, scraped_html, markdown, formatted_html, summary, read, starred
`

type UpdateArticleSetStarredValueParams struct {
	Starred int64
	ID      int64
}

func (q *Queries) UpdateArticleSetStarredValue(ctx context.Context, arg UpdateArticleSetStarredValueParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, updateArticleSetStarredValue, arg.Starred, arg.ID)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Link,
		&i.Published,
		&i.DateFound,
		&i.ScrapedHtml,
		&i.Markdown,
		&i.FormattedHtml,
		&i.Summary,
		&i.Read,
		&i.Starred,
	)
	return i, err
}
