// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const insertArticle = `-- name: InsertArticle :one
INSERT INTO articles (
	feed_id, 
	title, 
	link, 
	published, 
	date_found, 
	summary,
	scraped_html,
	article_content
) VALUES (
	 ?, 
	 ?, 
	 ?, 
	 ?, 
	 ?, 
	 ?, 
	 ?,
	 ?
 ) RETURNING id, feed_id, title, link, published, date_found, article_content, scraped_html, summary
`

type InsertArticleParams struct {
	FeedID         int64
	Title          string
	Link           string
	Published      *time.Time
	DateFound      *time.Time
	Summary        string
	ScrapedHtml    string
	ArticleContent string
}

func (q *Queries) InsertArticle(ctx context.Context, arg InsertArticleParams) (Article, error) {
	row := q.db.QueryRowContext(ctx, insertArticle,
		arg.FeedID,
		arg.Title,
		arg.Link,
		arg.Published,
		arg.DateFound,
		arg.Summary,
		arg.ScrapedHtml,
		arg.ArticleContent,
	)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.Title,
		&i.Link,
		&i.Published,
		&i.DateFound,
		&i.ArticleContent,
		&i.ScrapedHtml,
		&i.Summary,
	)
	return i, err
}

const insertFeed = `-- name: InsertFeed :one
 INSERT INTO feeds (
	url, 
	title, 
	css_sel_container,
	css_sel_start,
	css_sel_stop,
	html_extraction_strategy,
	last_fetched
) VALUES (
	?, 
	?, 
	?, 
	?, 
	?, 
	?, 
	CURRENT_TIMESTAMP
) RETURNING id, url, title, last_fetched, css_sel_container, css_sel_start, css_sel_stop, html_extraction_strategy
`

type InsertFeedParams struct {
	Url                    string
	Title                  string
	CssSelContainer        string
	CssSelStart            string
	CssSelStop             string
	HtmlExtractionStrategy string
}

func (q *Queries) InsertFeed(ctx context.Context, arg InsertFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, insertFeed,
		arg.Url,
		arg.Title,
		arg.CssSelContainer,
		arg.CssSelStart,
		arg.CssSelStop,
		arg.HtmlExtractionStrategy,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Title,
		&i.LastFetched,
		&i.CssSelContainer,
		&i.CssSelStart,
		&i.CssSelStop,
		&i.HtmlExtractionStrategy,
	)
	return i, err
}

const insertOrIgnoreArticle = `-- name: InsertOrIgnoreArticle :exec
;

INSERT OR IGNORE INTO articles (
	feed_id, 
	title, 
	link, 
	published, 
	date_found,
	summary,
	scraped_html,
	article_content 
) VALUES (
	 ?, 
	 ?, 
	 ?, 
	 ?,
	 ?, 
	 ?, 
	 ?, 
	 ?
 )
`

type InsertOrIgnoreArticleParams struct {
	FeedID         int64
	Title          string
	Link           string
	Published      *time.Time
	DateFound      *time.Time
	Summary        string
	ScrapedHtml    string
	ArticleContent string
}

func (q *Queries) InsertOrIgnoreArticle(ctx context.Context, arg InsertOrIgnoreArticleParams) error {
	_, err := q.db.ExecContext(ctx, insertOrIgnoreArticle,
		arg.FeedID,
		arg.Title,
		arg.Link,
		arg.Published,
		arg.DateFound,
		arg.Summary,
		arg.ScrapedHtml,
		arg.ArticleContent,
	)
	return err
}

const insertScraperRan = `-- name: InsertScraperRan :one
INSERT INTO log (
	articles_created, 
	run_type,
	time_ran
) VALUES (
	?,
	?, 
	CURRENT_TIMESTAMP
) RETURNING id, time_ran, run_type, articles_created
`

type InsertScraperRanParams struct {
	ArticlesCreated int64
	RunType         string
}

func (q *Queries) InsertScraperRan(ctx context.Context, arg InsertScraperRanParams) (Log, error) {
	row := q.db.QueryRowContext(ctx, insertScraperRan, arg.ArticlesCreated, arg.RunType)
	var i Log
	err := row.Scan(
		&i.ID,
		&i.TimeRan,
		&i.RunType,
		&i.ArticlesCreated,
	)
	return i, err
}

const selectAllFeeds = `-- name: SelectAllFeeds :many
SELECT id, url, title, last_fetched, css_sel_container, css_sel_start, css_sel_stop, html_extraction_strategy from feeds
`

func (q *Queries) SelectAllFeeds(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, selectAllFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Title,
			&i.LastFetched,
			&i.CssSelContainer,
			&i.CssSelStart,
			&i.CssSelStop,
			&i.HtmlExtractionStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
